base_dir: /glade/work/cschirninger/training/Muram_spatially_varying_r0_020_smooth
meta_state: 'none'
data:
  type: 'MURAM'
  data_path: '/glade/work/cschirninger/data/I_out_med.468000'
  n_images: 80
  pixel_per_ds: 511.5
  x_crop: 400
  y_crop: 400
  crop_size: 512
  psf_type: 'varying'

logging:
  project: NeuralBD
  name: MURAM

training:
  epochs: 10000
  log_every_n_steps: 100
  name: MURAM
  check_val_every_n_epoch: 10
model:
  dim: 512